plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "spec/spec_helper.rb"
    - "db/migrate/**/*"
    - "config/puma.rb"
    - "config/environments/**/*"
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Metrics/ClassLength:
  Max: 165

Metrics/ModuleLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Rails/HelperInstanceVariable:
  Enabled: false

Rails/ActiveRecordOverride:
  Exclude:
    - "app/models/membership.rb"

Rails/TransactionExitStatement:
  Exclude:
    - "app/models/action_item.rb"
    - "app/services/retrospectives/reveal.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "app/services/retrospectives/**/*.rb"
    - "spec/**/*"

Layout/LineLength:
  Max: 140
